employers/urls.py
from django.urls import path

from . import views

app_name='emplyer'

urlpatterns=[
    path('emplyrlogin',views.login,name="emplylogin"),
    path('emplyrhome',views.home,name="emplyhome")
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jb_seeker/',include('jobseeker.urls')),
    path('jb_admin/',include('jobadmin.urls')),
    path('emplyrs/',include('employers.urls'))
]

jobadmin/urls.py
from django.urls import path

from . import views

app_name='jobadmin'

urlpatterns=[
    
    path('admin_login',views.admin_login,name="admnlogin" ),
    path('signup',views.admin_signup,name="admin_signup"),
    path('emplyers_list',views.emplyers_lst,name="emp_list"),
]

jobseeker/urls.py
from django.urls import path

from . import views
app_name='jbskr'
urlpatterns=[
    path('login',views.login,name='login'),
    path('srch',views.search,name='search'),
    path('detls',views.details,name='details'),

]

employers/models.py
from django.db import models

# Create your models here.

jobadmin/models.py
from django.db import models

# Create your models here.

jobseeker/models.py
from django.db import models

# Create your models here.

employers/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,'employers/login.html')
def home(request):
    return render(request,'employers/home.html')

jobadmin/views.py
from django.shortcuts import render

# Create your views here.
def admin_login(request):
    return render(request,'jobadmin/login.html')
def admin_signup(request):
    return render(request,'jobadmin/signup.html')
def emplyers_lst(request):
    return render(request,'jobadmin/view_employers.html')
    

jobseeker/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,'jobseeker/login.html')

def search(request):
        return render(request,'jobseeker/job_search.html')
def details(request):
    return render(request,'jobseeker/job_details.html')


    

employers/templates/employers/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    home
    <img src="{% static 'images/project sign up.jpeg' %}" alt="">
    <a href="{% url 'emplyer:emplylogin' %}"> login </a>
</body>
</html>

employers/templates/employers/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <a href="{% url 'emplyer:emplyhome' %}">sign up </a>
    <br>
    login
    <img src="{% static 'images/project login.jpeg' %}" alt="">

    

</body>
</html>

jobadmin/templates/jobadmin/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  login

<a href="{% url 'jobadmin:admin_signup' %}">admin signup</a> <br><br>  
<img src="{% static 'images/glass.png' %}" alt="" height="150px"width="150px">

</body>
</html>

jobadmin/templates/jobadmin/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    sign up
    <img src="{% static 'images/project sign up.jpeg' %}" alt="">
    <a href="{% url 'jobadmin:emp_list' %}">empyers list </a>
</body>

</html>

jobadmin/templates/jobadmin/view_employers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    employers list
    <img src="{% static 'images/glass.png' %}" width="150px" height="150px" alt="">
    <a href="{% url 'jobadmin:admnlogin' %}">login</a>
  
   
</body>
</html>

jobseeker/templates/jobseeker/job_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   details
   <img src="{% static 'images/sm_5ab4a26e8d73b.jpg' %} " height="150px" width="150px" alt="">
   <a href="{% url 'jbskr:search' %}">search</a> 
</body>
</html>

jobseeker/templates/jobseeker/job_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    job search <br>
    <a href="{% url 'jbskr:details' %} " > job details</a>
    <br>
    <a href="{% url 'jbskr:login' %}" >login</a>
    
</body>
</html>

jobseeker/templates/jobseeker/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <h1>hello</h1>
    <a href="{% url 'jbskr:details' %}">job details</a>
    <img src="{% static 'images/project home.jpeg' %}" alt="" height="200px" width="100px">
</body>
</html>